CREATE TABLE IF NOT EXISTS movie_rental(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    conditions text NOT NULL CHECK (conditions <> ''),
    userid varchar(256),
    returndate date NOT NULL,
    daterental date NOT NULL
);

CREATE TABLE IF NOT EXISTS movie_rental_details(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
    movieid varchar(256),
    state varchar(20),
    isreturn BOOLEAN,
    movie_rentalId INTEGER REFERENCES movie_rental(id)
);